export { default as NewCase } from './NewCase.vue'
export { default as EditCase } from './EditCase.vue'
// export { default as EditCase } from './SocketIO.vue'
export { default as Layout } from './CaseLayout.vue'
export { default as Intro } from './CaseIntro.vue'